nombres = [
 'Chelsea',
 'Gabriela',
 'Simón',
 'Luisana',
 'Daniela',
 'Mark',
 'Bruno',
 'Edgar',
 'Joel',
 'Pamela',
 'Renee',
 'Christina',
 'Luz',
 'Cory',
 'Ana Laura',
 'Gonzalo',
 'Sara',
 'Isabel',
 'Emily',
 'Daniela Patricia',
 'Micaela',
 'Carmen Susana',
 'Néstor',
 'Manuela',
 'Javier Enrique',
 'Andrés Felipe',
 'José Antonio',
 'Agustina',
 'Stephen',
 'Angela',
 'Daniel',
 'Brandon',
 'Joseph',
 'Matthew',
 'Patricia',
 'Manuel',
 'Juan Segundo',
 'Samantha',
 'Milton',
 'Charles',
 'María José',
 'Loretta',
 'Valentina Gabriela',
 'FernandaNatalia',
 'Diane',
 'Antonio Ramón',
 'Marcela',
 'Eduardo',
 'Lucas',
 'Ignacio',
 'Romina',
 'Gregory',
 'Cristian',
 'Elena',
 'Florencia',
 'Jorge',
 'Marco',
 'Oscar',
 'Nelson',
 'Jennifer Micaela',
 'Mariano',
 'Bradley',
 'Catalina',
 'Paulina',
 'Monique',
 'Diego Alejandro',
 'Chris',
 'Jaime',
 'Isaac',
 'Eric Jonás',
 'Diego',
 'Miguel Ángel',
 'Rachel',
 'Mckenzie',
 'Eduardo Javier',
 'Martín',
 'Luna',
 'Nicolás',
 'Ricardo Alejandro',
 'Fernando',
 'Christy',
 'Javier',
 'Roberto José',
 'Constanza',
 'Tatiana',
 'Alejandra',
 'Liliana Raquel',
 'Silvana',
 'Meagan',
 'Alexis',
 'Cody',
 'Lorenzo Esteban',
 'Hannah',
 'Luisa',
 'Ryan',
 'Ana',
 'Vanessa',
 'Ramón',
 'Isabella Sofia',
 'Mario',
 'Jessica',
 'Randy',
 'Valentina',
 'Renato',
 'Laura Beatriz',
 'Sofía María',
 'Carolina Isabel',
 'Marcos',
 'Rosa Amelia',
 'Raúl',
 'Aurora',
 'José Manuel',
 'Ivonne',
 'Brandy',
 'James',
 'Keith',
 'Scott',
 'Antonio',
 'Solange',
 'Marcelo Ignacio',
 'Julie',
 'Karen',
 'Maria',
 'Esperanza',
 'Fernando Andrés',
 'Gregorio',
 'Katherine',
 'Celeste',
 'Tina',
 'Carmen',
 'Rufina',
 'Adriana',
 'Camila Valeria',
 'Aurelio',
 'Federico David',
 'Amanda',
 'Silvia',
 'Joshua',
 'Javiera',
 'Hugo',
 'Patrick',
 'Rita',
 'Pablo',
 'Mariana',
 'Germán',
 'Andreína',
 'Robin',
 'Heather',
 'Lourdes',
 'Brittany',
 'Gabriel',
 'Chase',
 'Guillermo',
 'Melissa',
 'Richard',
 'Felipe',
 'Holly',
 'María Laura',
 'Emilio',
 'Joaquín',
 'Mateo',
 'Lorena',
 'Paloma',
 'Luis',
 'Héctor',
 'Paola Andrea',
 'Mónica',
 'Carla',
 'Clara',
 'Larissa',
 'Rodrigo',
 'Carlos',
 'Juan Sebastián',
 'Verónica Gabriela',
 'Ximena',
 'Tiffany',
 'Juan José',
 'Juan Pablo',
 'Emilio Sebastián',
 'Natalia Alejandra',
 'Camila',
 'Linda',
 'Rodrigo Antonio',
 'Wanda',
 'Paige',
 'Noelia',
 'Ronald',
 'Cristina',
 'Tonya',
 'Michael',
 'Eric',
 'Stacy',
 'Edward',
 'Ángel',
 'Andrew',
 'Rebecca',
 'Gabriel Hernán',
 'Federico',
 'Isabel Carolina',
 'Alejandro',
 'Rosa',
 'Amy',
 'Martha',
 'Vanesa',
 'Amparo',
 'Juana',
 'Mauricio',
 'Moisés',
 'Megan',
 'Antonella',
 'Luciana',
 'Natalia',
 'Marina',
 'Sebastián',
 'Celestino',
 'Luis Alberto',
 'Claudia',
 'Yanina',
 'Jimmy',
 'Juan David',
 'Darius',
 'Elsa',
 'Crystal',
 'Miguel',
 'Jill',
 'Kristen',
 'Debra',
 'David',
 'Nayara',
 'Anna',
 'Shannon',
 'Gisela',
 'Tomás',
 'Adolfo',
 'Barbara',
 'José',
 'Jazmín',
 'Sarah',
 'Christopher',
 'Francisco',
 'Silvina',
 'Juan Carlos',
 'Sandra',
 'Carolina',
 'Jamie',
 'Justin',
 'Aaron',
 'Carla Fernanda',
 'Ana María',
 'Fabián',
 'Isabella',
 'Alicia',
 'René',
 'Robert',
 'Olga Marcela',
 'Rosario',
 'Aldo Manuel',
 'Ernesto',
 'Irene',
 'Valeria',
 'Evelina',
 'Elisa Patricia',
 'Brian',
 'Andrés',
 'Rufino',
 'Miranda',
 'Nadia',
 'Esteban',
 'Olga',
 'Rafael',
 'Arthur',
 'Rosa María',
 'Vicki',
 'Hernán',
 'María',
 'Leslie',
 'Mariana Fernanda',
 'Nieves',
 'Roberta',
 'Raul',
 'Ellen',
 'Sofía',
 'Ana Belén',
 'César',
 'Miriam',
 'Antonia',
 'Verónica',
 'Santiago',
 'Lisa',
 'Elizabeth',
 'Roberto',
 'Celia',
 'Jenna',
 'Gustavo',
 'Jimena',
 'Natalie',
 'Sergio',
 'Julieta',
 'Tracey',
 'Kevin',
 'Dana',
 'Lucía Camila',
 'Donna',
 'Juan',
 'Susana',
 'Benjamín',
 'Marcelo',
 'Lorenzo',
 'Evan',
 'José Luis',
 'Rocío',
 'José María',
 'Billy',
 'Eva',
 'Matías',
 'Mike',
 'Paula',
 'Enrique',
 'Pedro',
 'Nicole',
 'Monica',
 'Calvin',
 'Hernán Mauricio',
 'Lucía',
 'Feliciano',
 'Consuelo',
 'Katelyn',
 'Alberto',
 'Ruth',
 'Perry',
 'Roxana',
 'Anita',
 'Diana',
 'Ricardo',
 'Teresa',
 'Soledad',
 'Leonardo',
 'Benjamin',
 'Adán',
 'Tyler',
 'Belén',
 'Carlos Alberto',
 'Cecilia',
 'Marisol',
 'Iris',
 'Kenneth',
 'Carlos Eduardo',
 'Brenda',
 'Jason',
 'José Ignacio',
 'Elisa',
 'Ashley',
 'Jacqueline',
 'Laura',
 'Mónica Estefanía',
 'Michelle',
 'Mary',
 'Stephanie',
 'Jasmin',
 'John',
 'Pilar',
 'Giselle Luz',
 'Cassandra',
 'Jonathan',
 'Andre',
 'Bonnie',
 'Leticia',
 'Donald',
 'Victoria',
 'Parker',
 'Camilo',
 'Brandi',
 'Janice'
]

apellidos = [
 'Pino',
 'Romero Delgado',
 'Ponce',
 'Rojas',
 'Hernández',
 'Vásquez',
 'Morris',
 'Toro',
 'Pizarro',
 'Guerra',
 'Quinn',
 'Mckee',
 'Velasco Salinas',
 'Moreno',
 'Rojas Mendez',
 'Cuevas',
 'Aguilar',
 'Hernández Ramirez',
 'Phillips',
 'Roberts',
 'Torres',
 'Espinoza',
 'Sawyer',
 'Castillo',
 'Jara',
 'Orellana',
 'Pacheco',
 'Fuentes',
 'Valenzuela',
 'Barraza',
 'Vallejo',
 'Byrd',
 'Morales',
 'Bravo',
 'Wolfe',
 'Pérez Martínez',
 'Douglas',
 'Pereira',
 'Singleton',
 'Avery',
 'López',
 'Baldwin',
 'Salazar',
 'Silva Díaz',
 'Ahumada',
 'Cabrera',
 'Figueroa',
 'Mora',
 'Ford',
 'Miranda Silva',
 'Cifuentes',
 'Velasco',
 'Cisternas',
 'Jiménez Rodriguez',
 'Rodríguez',
 'Barrios',
 'Ramos',
 'Ruiz Torres',
 'Drake',
 'Reyes',
 'Luna',
 'Sanhueza',
 'Armstrong',
 'Carrillo',
 'Aranda',
 'Cortez',
 'Gross',
 'Sepúlveda',
 'Winters',
 'Ryan',
 'Torres López',
 'Russell',
 'Castro Ramírez',
 'Herrera',
 'Kennedy',
 'Mcdonald',
 'Campos',
 'Navarro Morales',
 'Edwards',
 'Campos Mendoza',
 'Larson',
 'Proctor',
 'Peterson',
 'Carrasco',
 'Méndez Castillo',
 'Logan',
 'Montenegro',
 'Fowler',
 'García Moreno',
 'Evans',
 'Brown',
 'Paredes',
 'Weich',
 'Floyd',
 'Miller',
 'Cooper',
 'Mendoza Aguilar',
 'Arias',
 'Benson',
 'Martin',
 'English',
 'San Martín',
 'Lyons',
 'Watkins',
 'Vargas Sánchez',
 'Cruz',
 'Horne',
 'Rice',
 'Lopez Rosales',
 'Medina',
 'Holt',
 'Maxwell',
 'Gutierrez Pinto',
 'Blair',
 'Molina Pérez',
 'Guzmán',
 'Ortiz',
 'Poblete',
 'Daniels',
 'Barton',
 'Romero',
 'Thompson',
 'Carvajal',
 'Castro',
 'Jones',
 'Díaz',
 'Peña',
 'Suarez Martínez',
 'Craig',
 'Cordero',
 'Ward',
 'Fuller',
 'Soto',
 'Shaw',
 'Jackson',
 'Powell',
 'Martínez Pérez',
 'Mitre Vazquez',
 'Whitehead',
 'Godoy',
 'Mendez',
 'Álvarez',
 'Williams',
 'Andrade Fuentes',
 'Mendoza',
 'Michael',
 'Cortés',
 'Myers',
 'Pérez',
 'Tucker',
 'Fernández',
 'King',
 'Blankenship',
 'Cohen',
 'Becerra',
 'Pezo',
 'Delgado Navarro',
 'Toledo',
 'Cisneros',
 'Suarez',
 'Farmer',
 'Saavedra',
 'Martínez',
 'Cortes Campos',
 'Rivas',
 'López González',
 'Delgado',
 'Tapia',
 'Graves',
 'Campbell',
 'Cordero Guzmán',
 'García',
 'Martinez',
 'Ríos',
 'Araujo',
 'León',
 'Hahn',
 'Gonzalez',
 'Mayo',
 'Mitchell',
 'Reed',
 'Sutton',
 'Hester',
 'Ramirez Diaz',
 'Borges',
 'Contreras',
 'Cabrera Vázquez',
 'Moore',
 'Lewis',
 'Sáez',
 'Riddle',
 'Pollard',
 'Wilson',
 'Lawson',
 'Aguilera',
 'Méndez',
 'Perez',
 'Marquez',
 'Garcia',
 'Abarca',
 'Frank',
 'Di Marco',
 'Vasquez',
 'Mason',
 'Smith',
 'Aguilar Cortes',
 'Lobos',
 'Howe',
 'García Morales',
 'Harris',
 'Nguyen',
 'Salinas Cordero',
 'Gómez',
 'Lara',
 'Parra',
 'Palma',
 'Downs',
 'Owens',
 'Lagos',
 'Rosario',
 'Kelly',
 'Davis',
 'Aguirre',
 'Gómez Torres',
 'Miranda',
 'Riquelme',
 'Lee',
 'Ramírez',
 'Castro Aguilar',
 'Román',
 'Rivera',
 'Stuart',
 'Ortiz García',
 'Justo Casares',
 'Casey',
 'Villalobos',
 'Randall',
 'Ross',
 'Escobar',
 'Erickson',
 'Franco',
 'Vargas',
 'Ruiz',
 'Parsons',
 'González',
 'Santos',
 'Montes',
 'Simpson',
 'Jiménez',
 'Bailey',
 'Sanchez García',
 'Riveros',
 'Bustamante',
 'Newman',
 'Bradford',
 'Sandoval',
 'Aravena',
 'Anderson',
 'Verdugo',
 'Matus',
 'Riley',
 'Valencia',
 'Villanueva',
 'Ibarra',
 'Lira',
 'Kim',
 'Ortega',
 'Curtis',
 'Gutiérrez',
 'Vidal',
 'Castañeda',
 'Valdez',
 'Araya',
 'Santos González',
 'Burns',
 'Ferrell',
 'Weiss',
 'Gutierrez',
 'Allen',
 'Osorio',
 'Olivares',
 'Navarro',
 'Stewart',
 'Friedman',
 'Atkins',
 'Goodwin',
 'Zapata',
 'González Fernández',
 'Cárdenas Valencia',
 'Molina',
 'Brooks',
 'Mann',
 'Ojeda',
 'Díaz Hernández',
 'Sanchez',
 'Watts',
 'Arancibia',
 'Rogers',
 'Silva',
 'Fernández García',
 'Bustos',
 'Bridges',
 'Salinas',
 'Palmer',
 'Ávila',
 'Guzmán Romero',
 'Muñoz',
 'Mills',
 'Sánchez',
 'Dean',
 'Camacho Cárdenas',
 'Gray',
 'Cáceres',
 'Valle',
 'Garza',
 'Reeves',
 'Vega',
 'Ríos Andrade',
 'Valdés',
 'Robinson',
 'Ulloa',
 'Catalán',
 'Reilly',
 'Bowen',
 'Johnson',
 'Zúñiga',
 'Flores',
 'Guerrero',
 'Valencia Ríos',
 'Pinto Gutiérrez',
 'Vergara',
 'Bautista',
 'Ferguson',
 'Flores Pérez',
 'Gallardo',
 'Fuentes Navarrete',
 'Long',
 'Leiva',
 'Crawford',
 'Diaz',
 'Hodge',
 'Rodríguez López'
]



experiencias_data = [
 'Redes Neuronales',
 'Internet de las Cosas (IoT)',
 'Optimización de Algoritmos',
 'Gestión de Datos',
 'Ciencia de Datos en Ingeniería Civil',
 'Inteligencia Artificial',
 'Ciencia de Datos en Geografía',
 'Bioinformática',
 'Ciencia de Datos Empresariales',
 'Ciencias Naturales',
 'Análisis de Series Temporales',
 'Bioestadística',
 'Optimización de Motores de Búsqueda',
 'Ingeniería de Datos en Sistemas de Información Geográfica (GIS)',
 'Ciencia de Datos en Ingeniería Mecánica',
 'Estadística Avanzada',
 'Análisis de Datos en Ciencia de Alimentos',
 'Modelado de Riesgos',
 'Ciencia de Datos en la Biotecnología',
 'Big Data',
 'Ciencia de Datos en la Medicina de Precisión',
 'Ingeniería de Datos en Ingeniería Eléctrica',
 'Análisis de Datos en Tiempo Real',
 'Procesamiento de Grandes Volúmenes de Datos',
 'Ciencia de Datos Geoespaciales',
 'Análisis de Datos Geoespaciales',
 'Análisis de Datos en la Industria Energética',
 'Ingeniería de Datos en Ciencias de la Comunicación',
 'Análisis de Datos en Periodismo',
 'Blockchain',
 'Programación',
 'Ingeniería de Datos en Química Computacional',
 'Análisis de Datos en Ingeniería Aeroespacial',
 'Gestión de Bases de Datos',
 'Análisis Predictivo',
 'Robótica',
 'Análisis Financiero',
 'Data Analytics',
 'Ciencia de Datos en Medicina',
 'Automatización de Procesos',
 'Ciencia de Datos en Derecho',
 'Ingeniería de Datos en la Nube',
 'Estadística',
 'Minería de Datos',
 'Cloud Computing',
 'Gestión de Proyectos',
 'Data Engineering',
 'Big Data en Ciencias Sociales',
 'Ingeniería de Datos en Producción Audiovisual',
 'Ingeniería de Datos en Trabajo Social',
 'Ciencia de Datos',
 'Optimización de Procesos',
 'Análisis de Datos en la Ecología',
 'Ingeniería de Datos en la Investigación de Mercado',
 'Ingeniería de Software',
 'Ciencia de Datos en la Economía del Comportamiento',
 'Análisis de Datos en Física de Partículas',
 'Realidad Virtual',
 'Investigación de Mercado',
 'Análisis de Datos en Educación Especial',
 'Ciencia de Datos en Geología',
 'Minería de Texto',
 'Estadística Aplicada',
 'Análisis de Datos de Sensores',
 'Análisis de Datos en la Industria Financiera',
 'Análisis de Datos en la Genómica',
 'Ciencia de Datos en Cinematografía',
 'Análisis de Datos de Redes Sociales',
 'Desarrollo de Aplicaciones Móviles',
 'Ciencia de Datos en Psicopedagogía',
 'Ciencia de Datos en la Educación',
 'Ciencia de Datos en la Salud',
 'Ingeniería de Datos en la Automatización Industrial',
 'Ingeniería de Sistemas',
 'Machine Learning',
 'Desarrollo de Sistemas de Recomendación',
 'Ciencia de Datos en la Nube',
 'Visualización de Datos',
 'Procesamiento de Lenguaje Natural',
 'Econometría',
 'Ciencia de Datos en la Agricultura',
 'Business Intelligence',
 'Data Science',
 'Análisis de Datos en la Industria de la Logística',
 'Desarrollo de Videojuegos',
 'Ingeniería de Datos en Ingeniería Química',
 'Investigación Científica',
 'Análisis de Datos en Psicología Experimental',
 'Ingeniería de Datos en la Internet de las Cosas (IoT)',
 'Análisis de Mercado',
 'Gestión de Datos Empresariales',
 'Deep Learning',
 'Ciencia de Datos en Psicología Clínica',
 'Ciencia de Datos en la Astronomía',
 'Análisis Legal de Datos',
 'Ciencia de Datos en Relaciones Públicas',
 'Ciberseguridad'
 ]

experiencias_finanzas = [
 'Gestión de Activos Financieros',
 'Auditoría Financiera',
 'Planificación de Finanzas Internacionales',
 'Estrategias de Financiamiento Empresarial',
 'Planificación de Estrategias de Desarrollo Empresarial',
 'Valoración de Empresas',
 'Estudios de Viabilidad Económica',
 'Reestructuración Financiera',
 'Planificación Financiera Empresarial',
 'Presupuesto y Control de Gastos',
 'Valoración de Activos y Pasivos',
 'Contabilidad Financiera',
 'Control de Proyectos Empresariales',
 'Planificación de Impuestos',
 'Finanzas Cuantitativas',
 'Optimización de Recursos en Proyectos',
 'Modelos de Negocio',
 'Gestión de Capital de Trabajo',
 'Gestión de Liquidez',
 'Gestión de Proyectos de Tecnología Financiera',
 'Planificación Estratégica de Finanzas Corporativas',
 'Finanzas Corporativas',
 'Planificación de Fusiones y Adquisiciones',
 'Evaluación de Riesgos en el Entorno Financiero',
 'Planificación de Tesorería',
 'Análisis de Costos y Beneficios en Negocios',
 'Análisis de Mercados Financieros',
 'Valoración de Instrumentos Financieros',
 'Modelos de Valoración de Activos',
 'Planificación Estratégica Financiera',
 'Gestión de Recursos Financieros',
 'Análisis de Fusiones y Adquisiciones de Empresas',
 'Análisis de Mercado de Capitales en Empresas',
 'Gestión de Activos Empresariales',
 'Planificación de Inversiones Estratégicas',
 'Evaluación de Rendimiento de Proyectos',
 'Administración de Carteras',
 'Análisis de Estrategias de Mercado',
 'Gestión de Proyectos de Infraestructura',
 'Análisis de Rentabilidad de Proyectos',
 'Análisis de Ciclo de Vida de Proyectos',
 'Análisis de Riesgos de Proyectos Empresariales',
 'Gestión de Proyectos de Desarrollo Inmobiliario',
 'Evaluación de Riesgos Financieros',
 'Análisis de Flujo de Efectivo',
 'Gestión de Portafolios de Inversión',
 'Gestión de Capital de Riesgo',
 'Gestión de Capital en Negocios',
 'Gestión de Recursos Financieros Corporativos',
 'Desarrollo de Estrategias de Inversión',
 'Análisis de Indicadores Financieros',
 'Gestión de Proyectos Financieros',
 'Análisis de Rentabilidad de Negocios',
 'Análisis de Rentabilidad',
 'Evaluación de Proyectos de Inversión',
 'Finanzas Personales',
 'Valoración de Proyectos de Inversión Empresarial',
 'Gestión de Fondos de Inversión',
 'Estrategias de Financiamiento',
 'Evaluación de Proyectos de Desarrollo',
 'Finanzas Internacionales',
 'Análisis de Costos y Beneficios',
 'Análisis de Viabilidad de Negocios',
 'Análisis de Inversiones',
 'Optimización de la Cadena de Suministro',
 'Análisis de Mercado de Capitales',
 'Evaluación de Rendimiento de Carteras',
 'Modelos de Pronóstico Financiero',
 'Gestión de Liquidez Empresarial',
 'Gestión de Carteras de Inversiones',
 'Gestión de Riesgos Empresariales',
 'Gestión de Riesgos Corporativos'
]

experiencias_RRHH = [
 'Psicología del Emprendimiento',
 'Psicología del Trabajo',
 'Psicología del Cambio Organizacional',
 'Ciencias de la Comunicación',
 'Coaching Organizacional',
 'Psicología del Conflicto en el Trabajo',
 'Entrevistas de Selección',
 'Psicología del Trabajo Remoto',
 'Evaluación en Procesos de Capacitación Laboral',
 'Psicología de la Comunicación en el Trabajo',
 'Psicología de la Salud Ocupacional',
 'Análisis de Políticas Públicas',
 'Evaluación en Procesos de Movilidad Interna',
 'Evaluación Psicolaboral',
 'Diseño de Procesos de Selección',
 'Evaluación de Cultura Organizacional en Selección',
 'Evaluación de Competencias en RRHH',
 'Gestión del Talento',
 'Trabajo Social',
 'Evaluación de Estrategias de Motivación en el Trabajo',
 'Evaluación de Cultura Organizacional',
 'Psicología de la Diversidad e Inclusión en el Trabajo',
 'Ciencias Políticas',
 'Relaciones Públicas',
 'Economía del Comportamiento',
 'Entrevistas de Evaluación Psicológica',
 'Psicología de Grupos y Equipos de Trabajo',
 'Evaluación de Competencias Laborales',
 'Psicología de la Motivación',
 'Psicología de la Calidad de Vida Laboral',
 'Psicología Social',
 'Evaluación del Clima Laboral',
 'Evaluación en Procesos de Promoción Interna',
 'Evaluación de Potencial en RRHH',
 'Antropología Cultural',
 'Evaluación 360 Grados',
 'Evaluación de Desempeño',
 'Evaluación del Clima Laboral en RRHH',
 'Evaluación Psicolaboral en Selección',
 'Medicina',
 'Evaluación de Recursos Humanos',
 'Selección por Competencias',
 'Desarrollo Organizacional',
 'Educación Especial',
 'Neurociencia',
 'Psicometría en la Selección de Personal',
 'Gestión de Talento Humano',
 'Psicología Laboral en el Ámbito de la Educación',
 'Evaluación de Culturas Multiculturales en Organizaciones',
 'Evaluación de Habilidades Sociales',
 'Evaluación Psicométrica',
 'Evaluación de Personalidad en el Trabajo',
 'Gestión de Procesos de Selección',
 'Terapia Cognitivo-Conductual',
 'Evaluación en Procesos de Desarrollo de Carrera',
 'Psicología de la Adquisición de Habilidades',
 'Psicología del Trabajo y la Familia',
 'Evaluación en Procesos de Desvinculación Laboral en RRHH',
 'Evaluación de Candidatos',
 'Psicología del Trabajo en Entornos Virtuales',
 'Evaluación en Procesos de Desvinculación Laboral',
 'Evaluación de Habilidades para el Trabajo',
 'Psicología Clínica',
 'Historia del Arte',
 'Psicología del Liderazgo',
 'Evaluación de Referencias Laborales',
 'Psicopedagogía',
 'Psicología Organizacional',
 'Selección por Competencias en RRHH',
 'Diseño de Pruebas de Selección',
 'Psicología del Desempeño en Equipos Multidisciplinarios',
 'Evaluación de Estrés Laboral',
 'Evaluación de Aptitudes',
 'Evaluación Psicológica en el Trabajo',
 'Evaluación de Competencias Gerenciales',
 'Evaluación de Riesgos Psicosociales',
 'Gestión de Recursos Humanos',
 'Reclutamiento de Personal',
 'Selección de Talento',
 'Gestión de Recursos Humanos Empresariales',
 'Selección de Personal',
 'Educación a Distancia',
 'Psicometría',
 'Evaluación de Entrevistas de Trabajo',
 'Psicología Experimental'
]

experiencias_web = [
 'Diseño de Comercio Electrónico',
 'Diseño Industrial',
 'Diseño de Aplicaciones Web',
 'Optimización de Motores de Búsqueda (SEO)',
 'Programación Frontend (HTML, CSS, JavaScript)',
 'Desarrollo Backend (Node.js, Ruby on Rails, Django, etc.)',
 'JavaScript',
 'Desarrollo de Portales Web',
 'Diseño de Blogs',
 'Diseño de Sistemas de Reservas en Línea',
 'Diseño de Sitios Web',
 'Diseño de Plataformas de Deportes en Línea',
 'Gestión de Contenido (CMS) en Sitios Web',
 'Animación Web y Experiencia Interactiva',
 'Diseño de Aplicaciones Móviles',
 'Diseño de Aplicaciones de Viajes en Línea',
 'Diseño de Plataformas de Cine en Línea',
 'HTML/CSS',
 'Diseño de Plataformas de Noticias en Línea',
 'Diseño de Plataformas de Streaming de Video en Línea',
 'Desarrollo Backend',
 'Optimización de Rendimiento Web',
 'Desarrollo de Portales de Noticias',
 'Diseño de Plataformas de Alimentos en Línea',
 'Marketing',
 'Desarrollo Web',
 'Desarrollo de Temas WordPress',
 'Seguridad Web y Desarrollo Seguro',
 'Frameworks Backend (por ejemplo, Node.js, Ruby on Rails, Django)',
 'Diseño Responsivo',
 'Desarrollo de Aplicaciones Web',
 'Desarrollo Frontend',
 'Gestión de Contenido (CMS)',
 'Desarrollo de Sitios Móviles',
 'Diseño de Plataformas de Venta en Línea',
 'Diseño de Plataformas de Viajes en Línea',
 'Gestión de Proyectos Web',
 'Testing y Depuración de Aplicaciones Web',
 'Diseño de Plataformas de Comida a Domicilio en Línea',
 'Diseño de Sitios Web de Reservas de Hoteles',
 'Diseño de Plataformas de Streaming de Video',
 'Bases de Datos Web',
 'Desarrollo de Sitios Web Responsivos',
 'Diseño Gráfico',
 'eCommerce',
 'Frameworks Frontend (por ejemplo, React, Angular, Vue)',
 'Desarrollo de Plataformas de Redes Sociales',
 'Diseño de Plataformas de Comercio Electrónico en Línea',
 'Full Stack Web Development',
 'Desarrollo de Portafolios en Línea',
 'Desarrollo de Tiendas en Línea',
 'Desarrollo de Plataformas E-learning',
 'Diseño de Experiencia de Usuario',
 'Diseño de Experiencia de Usuario (UX)',
 'Diseño de Sistemas de Gestión de Contenido',
 'Diseño de Foros en Línea',
 'Animación Web',
 'Diseño de Tiendas en Línea',
 'Arquitectura de Software Web',
 'Diseño de Interfaces de Usuario (UI/UX)',
 'Diseño de Plataformas de Aprendizaje en Línea',
 'Diseño de Plataformas de Juegos en Línea',
 'Desarrollo de Aplicaciones Móviles',
 'Integración de APIs',
 'Integración de APIs en Aplicaciones Web',
 'Testing y Depuración Web',
 'Bases de Datos Web y Backend',
 'Diseño de Base de Datos Web',
 'Seguridad Web',
 'Diseño de Interfaz de Usuario (UI)',
 'SEO (Optimización de Motores de Búsqueda)',
 'Diseño Gráfico Web',
 'Diseño de Plataformas de Música en Línea',
 'Programación Web',
 'Diseño de Portafolios en Línea',
 'Desarrollo Full Stack'
]



habilidades_data_web = [
 'Habilidad para Motivar en Tareas Analíticas',
 'Escucha Activa',
 'Colaboración Internacional',
 'Habilidad para Planificar y Priorizar',
 'Habilidad para Construir Relaciones Duraderas',
 'Habilidad para la Gestión de Proyectos',
 'Habilidad de Toma de Decisiones en Datos',
 'Comunicación Intercultural',
 'Habilidad de Colaboración en Equipo',
 'Colaboración en Equipos Multidisciplinarios',
 'Comunicación Persuasiva',
 'Autonomía',
 'Confianza en la Comunicación Técnica',
 'Relaciones Interpersonales',
 'Capacidad para Trabajar en Red',
 'Habilidades de Networking',
 'Compromiso con la Calidad de Resultados',
 'Habilidad para Escuchar',
 'Resolución de Problemas Creativa',
 'Pensamiento Analítico Crítico',
 'Predispocición a la acción',
 'Trabajo en Equipo Multicultural',
 'Gestión de Equipos Virtuales',
 'Compromiso',
 'Habilidad para Trabajar Bajo Presión',
 'Comunicación Transparente',
 'Habilidad de Resolución de Conflictos',
 'Asertividad',
 'Habilidad de Coaching',
 'Comunicación Efectiva',
 'Capacidad para Inspirar',
 'Colaboración Interdisciplinaria',
 'Aprendizaje Continuo en Nuevas Tecnologías',
 'Comunicación en Entornos Virtuales',
 'Facilitación de Reuniones Efectivas',
 'Trabajo en Equipo',
 'Iniciativa',
 'Gestión de Expectativas',
 'Flexibilidad',
 'Honestidad',
 'Empatía',
 'Gestión de Conflictos en Desarrollo de Datos',
 'Respeto por la Diversidad de Enfoques',
 'Aprendizaje Continuo',
 'Habilidad de Comunicación Escrita',
 'Gestión de Reuniones Virtuales',
 'Autocontrol',
 'Gestión de Proyectos',
 'Escucha Activa para Comprender Necesidades',
 'Comunicación Empresarial',
 'Capacidad de Resolución de Problemas en Grupo',
 'Respeto',
 'Habilidad de Comunicación Oral',
 'Gestión Efectiva del Tiempo',
 'Gestión de Reuniones',
 'Capacidad para Mantener la Motivación a Distancia',
 'Adaptabilidad a Cambios Tecnológicos',
 'Habilidad para la Gestión de Cambios',
 'Gestión de la Comunicación en Línea',
 'Adaptabilidad al Trabajo Remoto',
 'Comunicación Clara y Concisa',
 'Adaptabilidad al Cambio',
 'Toma de Decisiones',
 'Integridad',
 'Gestión de Expectativas en Análisis de Datos',
 'Resiliencia',
 'Liderazgo de Equipos',
 'Habilidad para Solucionar Problemas a Distancia',
 'Habilidad para Negociar Acuerdos',
 'Habilidad para Resolver Conflictos',
 'Trabajo en Equipo en Proyectos Colaborativos',
 'Liderazgo',
 'Habilidad para Adaptarme a Diferentes Estilos de Trabajo',
 'Resolución de Problemas',
 'Manejo de Crisis',
 'Gestión del Tiempo',
 'Ética Profesional',
 'Comunicación Interpersonal',
 'Mentoría a Nuevos Profesionales en el Equipo',
 'Habilidad de Motivación',
 'Liderazgo Técnico en Proyectos Data Science',
 'Inteligencia Emocional',
 'Pensamiento Estratégico',
 'Comunicación a Través de Plataformas Digitales',
 'Empatía con Compañeros y Usuarios',
 'Habilidad para Trabajar en Ambientes Multitarea',
 'Pensamiento Analítico',
 'Gestión de Equipos Globales',
 'Trabajo en Equipo Virtual',
 'Capacidad de Negociación',
 'Capacidad de Delegación',
 'Gestión de Tiempo Virtual',
 'Gestión de la Diversidad',
 'Habilidad para Dar y Recibir Retroalimentación',
 'Habilidad de Escritura Profesional',
 'Gestión de Proyectos Técnicos',
 'Gestión de Equipos',
 'Pensamiento Crítico y Resolución de Problemas',
 'Gestión de Reuniones Efectivas',
 'Capacidad para Liderar Equipos Remotos',
 'Colaboración',
 'Comunicación No Verbal',
 'Comunicación Virtual Efectiva',
 'Mentoría',
 'Diplomacia',
 'Habilidades de Colaboración Remota',
 'Habilidad para Tomar Iniciativa',
 'Comunicación Efectiva de Resultados Técnicos',
 'Creatividad',
 'Respeto por la Diversidad',
 'Pensamiento Crítico',
 'Autonomía y Proactividad',
 'Adaptabilidad',
 'Capacidad de Influencia',
 'Capacidad de Organización',
 'Comunicación Intercultural en Línea',
 'Comunicación Transparente de Procesos',
 'Gestión de Conflictos',
 'Gestión de Estrés',
 'Confianza',
 'Capacidad para Manejar Críticas Constructivas',
 'Iniciativa en la Mejora de Procesos',
 'Habilidad para Fomentar la Creatividad',
 'Habilidad de Presentación'
]

habilidades_finanzas_RRHH = [
 'Escucha Activa',
 'Colaboración Internacional',
 'Habilidad para Planificar y Priorizar',
 'Habilidad para Construir Relaciones Duraderas',
 'Habilidad para la Gestión de Proyectos',
 'Comunicación Intercultural',
 'Habilidad de Colaboración en Equipo',
 'Colaboración en Equipos Multidisciplinarios',
 'Comunicación Transparente en Finanzas',
 'Comunicación Persuasiva',
 'Autonomía',
 'Relaciones Interpersonales',
 'Capacidad para Trabajar en Red',
 'Habilidades de Networking',
 'Habilidad para Escuchar',
 'Resolución de Problemas Creativa',
 'Pensamiento Analítico Crítico',
 'Predispocición a la acción',
 'Trabajo en Equipo Multicultural',
 'Planificación Financiera',
 'Gestión de Equipos Virtuales',
 'Compromiso',
 'Habilidad para Trabajar Bajo Presión',
 'Comunicación Transparente',
 'Resolución de Conflictos Laborales',
 'Habilidad de Resolución de Conflictos',
 'Asertividad',
 'Habilidad de Coaching',
 'Comunicación Efectiva',
 'Capacidad para Inspirar',
 'Colaboración Interdisciplinaria',
 'Comunicación en Entornos Virtuales',
 'Facilitación de Reuniones Efectivas',
 'Trabajo en Equipo',
 'Iniciativa',
 'Gestión de Expectativas',
 'Habilidad de Comunicación en Recursos Humanos',
 'Gestión de Reuniones Efectivas en RRHH',
 'Flexibilidad',
 'Honestidad',
 'Empatía',
 'Aprendizaje Continuo',
 'Habilidad de Comunicación Escrita',
 'Gestión de Proyectos Financieros',
 'Gestión de Reuniones Virtuales',
 'Facilitación de Reuniones Estratégicas',
 'Autocontrol',
 'Gestión de Proyectos',
 'Ética Profesional en Finanzas',
 'Comunicación Empresarial',
 'Capacidad de Resolución de Problemas en Grupo',
 'Diplomacia en Negocios',
 'Respeto',
 'Habilidad de Comunicación Oral',
 'Gestión Efectiva del Tiempo',
 'Gestión de Reuniones',
 'Capacidad para Mantener la Motivación a Distancia',
 'Habilidad para la Gestión de Cambios',
 'Gestión de la Comunicación en Línea',
 'Adaptabilidad al Trabajo Remoto',
 'Comunicación Clara y Concisa',
 'Adaptabilidad al Cambio',
 'Liderazgo de Equipos Multiculturales',
 'Toma de Decisiones',
 'Integridad',
 'Resiliencia',
 'Liderazgo de Equipos',
 'Habilidad para Solucionar Problemas a Distancia',
 'Habilidad para Negociar Acuerdos',
 'Habilidad para Resolver Conflictos',
 'Liderazgo',
 'Habilidad para Adaptarme a Diferentes Estilos de Trabajo',
 'Resolución de Problemas',
 'Manejo de Crisis',
 'Gestión del Tiempo',
 'Negociación Estratégica',
 'Ética Profesional',
 'Comunicación Interpersonal',
 'Habilidad de Motivación',
 'Desarrollo de Estrategias Financieras',
 'Inteligencia Emocional',
 'Pensamiento Estratégico',
 'Comunicación a Través de Plataformas Digitales',
 'Habilidad para Trabajar en Ambientes Multitarea',
 'Respeto por la Diversidad en RRHH',
 'Pensamiento Analítico',
 'Gestión de Equipos Globales',
 'Trabajo en Equipo Virtual',
 'Capacidad de Negociación',
 'Capacidad de Delegación',
 'Mentoría en Recursos Humanos',
 'Gestión de Tiempo Virtual',
 'Gestión de la Diversidad',
 'Habilidad para Dar y Recibir Retroalimentación',
 'Habilidad de Escritura Profesional',
 'Gestión de Equipos',
 'Gestión de Reuniones Efectivas',
 'Capacidad para Liderar Equipos Remotos',
 'Colaboración',
 'Comunicación No Verbal',
 'Gestión Efectiva del Tiempo en Finanzas',
 'Comunicación Virtual Efectiva',
 'Mentoría',
 'Diplomacia',
 'Habilidades de Colaboración Remota',
 'Habilidad para Tomar Iniciativa',
 'Creatividad',
 'Respeto por la Diversidad',
 'Pensamiento Crítico',
 'Gestión de Recursos Humanos',
 'Autonomía y Proactividad',
 'Adaptabilidad',
 'Capacidad de Influencia',
 'Capacidad de Organización',
 'Comunicación Intercultural en Línea',
 'Gestión de Conflictos',
 'Gestión de Estrés',
 'Confianza',
 'Capacidad para Manejar Críticas Constructivas',
 'Habilidad para Fomentar la Creatividad',
 'Habilidad de Presentación'
]



herramientas_data = [
 'RapidMiner Studio',
 'Metasploit',
 'GitLab',
 'Cypress',
 'Plotly',
 'Ganache',
 'XGBoost',
 'Statistical Modeling',
 'LightGBM',
 'Six Sigma',
 'Dataiku DSS',
 'IBM SPSS',
 'Asana',
 'SQL Server',
 'Zapier',
 'Docker',
 'TOGAF',
 'Stellar',
 'Data Integration',
 'Lean',
 'Snowflake',
 'AutoCAD',
 'ISO 9001',
 'FastText',
 'AIOps (Artificial Intelligence for IT Operations)',
 'Azure DevOps',
 'GitHub',
 'Project Management Tools (Jira, Trello)',
 'Jenkins',
 'Data Ethics',
 'D3.js',
 'BERT',
 'Postman',
 'Version Control',
 'Unreal Engine',
 'Sisense',
 'ELK Stack (Elasticsearch, Logstash, Kibana)',
 'CI/CD (Continuous Integration/Continuous Deployment)',
 'Containerization',
 'Kanban',
 'Hive',
 'Automated Testing',
 'OpenCV',
 'Quantum Programming',
 'Monday.com',
 'Oracle Exadata',
 'MLflow',
 'Database Management Systems (DBMS)',
 'Python',
 'Oracle',
 'DevOps',
 'Express.js',
 'Git',
 'React',
 'AWS Glue',
 'Airtable',
 'Azure',
 'Computer Vision',
 'Splunk',
 'Anaconda',
 'R',
 'Data Catalogs',
 'Zeppelin',
 '3D Printing',
 'Nagios',
 'Hugging Face Transformers',
 'Langchain',
 'Amazon Web Services (AWS)',
 'QlikView',
 'GRU (Gated Recurrent Unit)',
 'Tableau',
 'Microsoft Azure',
 'Apache Cassandra',
 'Big Data',
 'Pinecone',
 'Cardano',
 'AutoML (Automated Machine Learning)',
 'AR/VR (Augmented Reality/Virtual Reality)',
 'PRINCE2',
 'Apache Solr',
 'Databricks',
 'Microsoft Azure Machine Learning',
 'Dataiku',
 'Google Cloud AI Platform',
 'C++',
 'New Relic',
 'LaTeX',
 'Trello',
 'ETL (Extracción, Transformación y Carga)',
 'Data Lakes',
 'Search Engine Optimization (SEO)',
 'Zephyr',
 'SciPy',
 'Google Cloud Platform (GCP)',
 'CircleCI',
 'SAS Enterprise Miner',
 'PyCharm',
 'Redis',
 'IBM Watson',
 'Selenium Grid',
 'Cucumber',
 'OpenAI GPT-3',
 'Hadoop',
 'Data Warehousing',
 'TeamCity',
 'PostgreSQL',
 'Azure Data Factory',
 'Teradata',
 'Maya',
 'TestNG',
 'LSTM (Long Short-Term Memory)',
 'WordPress',
 'Flask-RESTful',
 'Data Governance Tools',
 'Reinforcement Learning (Aprendizaje por Refuerzo)',
 'Flume',
 'NLTK (Natural Language Toolkit)',
 'Node.js',
 'Microsoft Quantum Development Kit',
 'Time Series Analysis',
 'Kubernetes',
 'Spacy',
 'PyTorch',
 'Data Science Platforms',
 'Web Development Frameworks (Flask, Django)',
 'Alteryx Designer',
 'Django Rest Framework',
 'Cloud Computing',
 'OWASP',
 'SAS Analytics',
 'Business Intelligence (BI) Tools',
 'Data Preprocessing',
 'Technical Writing',
 'DataBricks',
 'Data Engineering',
 'Llama (Meta)',
 'Hyperledger',
 'Apache Impala',
 'RapidMiner',
 'DataRobot',
 'Redshift',
 'Spark',
 'StatsModels',
 'Text Editors (Sublime Text, Atom)',
 'Data Mining',
 'Blender',
 'Streamlit',
 'code-llama',
 'Data Cleaning',
 'NoSQL Databases (MongoDB, Cassandra)',
 'Cybersecurity',
 'JUnit',
 'IOTA',
 'Data Pipelines',
 'Confluence',
 'Markdown Editors',
 'ETL Tools (Talend, Informatica)',
 'Google Colab',
 'Alteryx',
 'Reinforcement Learning',
 'Google AutoML',
 'Qlik Sense',
 'WordPress Development',
 'MapReduce',
 'IBM Qiskit',
 'Agile Methodology',
 'Quantum Computing',
 'Bitbucket',
 'Jupyter Notebook',
 'MongoDB',
 'Scikit-learn',
 'HBase',
 'Virtualization (VirtualBox, VMware)',
 'NoSQL Databases',
 'Scikit-Learn',
 'Prometheus',
 'CosmosDB',
 'Data Visualization Libraries (matplotlib, seaborn)',
 'ISO 27001',
 'Data Warehouse Platforms',
 'Quality Assurance (QA)',
 'Pentaho',
 'Word2Vec',
 'AllenNLP',
 'Unity',
 'NLTK',
 'Relational Databases',
 'Keras',
 'Chroma',
 'API Documentation',
 'Apache Hive',
 'Kubeflow',
 'Data Analytics Software',
 'Notion',
 'Ethereum',
 'Search Engine Marketing (SEM)',
 'Pig',
 'Bokeh',
 'Web Analytics',
 'Data Architecture',
 'Nmap',
 'Blockchain Technology',
 'Selenium',
 'Continuous Monitoring',
 'Sqoop',
 'Travis CI',
 'Technical Documentation',
 'MySQL',
 'RESTful API',
 'Data Analysis Tools (Pandas, NumPy, Jupyter)',
 'Email Marketing',
 'Cloudera',
 'Looker',
 'Caffe',
 'Elasticsearch',
 'Microsoft SQL Server',
 'Machine Learning',
 'User Manuals',
 'Responsive Web Design',
 'UI/UX Design',
 'Scrum',
 'ITIL',
 'Azure Web Services',
 'Apache Flink',
 'Network Security',
 'PySpark',
 'Web3.js',
 'Statistical Software (R, SAS)',
 'MXNet',
 'Google BigQuery',
 'Vue.js',
 'Gensim',
 'Robotics',
 'Dash by Plotly',
 'Visual Studio Code',
 'Data Quality',
 'Content Management Systems (CMS)',
 'Microsoft Excel',
 'JIRA',
 'Wireshark',
 'TensorFlow, Keras, PyTorch',
 'TensorFlow',
 'IoT (Internet of Things)',
 'Documentation Tools (Confluence, Markdown)',
 'Talend',
 'Predictive Analytics',
 'Bash Scripting',
 'DVC (Data Version Control)',
 'IBM Cloud',
 'Informatica PowerCenter',
 'Grafana',
 'TestRail',
 'Apache Beam',
 'Google Data Studio',
 'Excel Power Query',
 'Natural Language Processing (NLP)',
 'Data Visualization',
 'IBM Watson Studio',
 'Linux/Unix',
 'Transformer',
 'Data Security',
 'Social Media Marketing',
 'Truffle',
 'Slack',
 'Knime',
 'spaCy',
 'Cassandra',
 'Apache NiFi',
 'Google Analytics',
 'Solidity',
 'Deep Learning',
 'Swagger',
 'SQL',
 'Machine Learning Ops (MLOps)',
 'Applitools',
 'Data Governance',
 'AWS SageMaker',
 'Front-End Development (HTML, CSS, JavaScript)',
 'Data Modeling',
 'Data Manipulation Libraries (pandas, numpy)',
 'Power BI',
 'Apache Kafka',
 'Robot Framework',
 'Hortonworks'
 ]

herramientas_finanzas = [
 'Float',
 'Paychex',
 'Salesforce',
 'SEMrush',
 'Sage 100cloud',
 'Taulia',
 'Zoho Analytics',
 'Harvest',
 'HubSpot CRM',
 'Trello',
 'Zapier',
 'Mint',
 'SAP Concur',
 'Hootsuite',
 'Quicken',
 'MS Dynamics 365',
 'FreshBooks',
 'QuickBooks',
 'Netsuite ERP',
 'Gusto',
 'TurboTax',
 'Wells Fargo Business Online',
 'Zoho Books',
 'Stripe',
 'Kabbage',
 'Sisense',
 'TSheets',
 'NetSuite',
 'Zendesk',
 'Monday.com',
 'Excel',
 'Workday Financial Management',
 'PayPal',
 'Xero',
 'Slack',
 'Chase for Business',
 'Bloomberg Terminal',
 'Sage 50cloud',
 'Office',
 'Google Analytics',
 'Paycom',
 'QuickBooks Online',
 'Expensify',
 'Tableau',
 'Basecamp',
 'Sage Intacct',
 'Acumatica',
 'Square',
 'Oracle E-Business Suite',
 'SAP ERP',
 'Wagepoint',
 'Shopify',
 'Kashoo',
 'Chargebee',
 'Power BI',
 'Chime',
 'SAP Business One',
 'Wave Financial'
]

herramientas_RRHH = [
 'Dice',
 'PeopleSoft',
 'RecruitLoop',
 'Paychex',
 'Breezy HR',
 'LinkedIn Recruiter',
 'Glassdoor for Employers',
 'Talentsoft',
 'ClearCompany',
 'LinkedIn Talent Solutions',
 'SAP SuccessFactors',
 'Kronos',
 'Assessment Tools',
 'Interview Scheduling Software',
 'Workday',
 'Lever',
 'HR Analytics Tools',
 'iCIMS',
 'Employee Engagement Platforms',
 'Applicant Tracking Systems (ATS)',
 'HR Chatbots',
 'UltiPro',
 'Zenefits',
 'Background Check Services',
 'Workforce Planning Tools',
 'HR Document Management Software',
 'ZipRecruiter',
 'Onboarding Software',
 'Benefits Administration Software',
 'Bullhorn',
 'Namely',
 'SmartRecruiters',
 'Employee Benefits Platforms',
 'Monster',
 'Recruitee',
 'BambooHR',
 'Hyrell',
 'Workable',
 'Job Boards (e.g., Indeed, Glassdoor)',
 'Video Interviewing Platforms',
 'Ceridian',
 'Recruiterbox',
 'HRsmart',
 'Employee Wellness Programs',
 'HR Compliance Software',
 'CareerBuilder for Employers',
 'Performance Management Software',
 'Paylocity',
 'Greenhouse',
 'JazzHR',
 'Employee Recognition Software',
 'Recruitment Marketing Platforms',
 'SilkRoad',
 'Jobvite',
 'Taleo',
 'Payroll Software',
 'Newton',
 'Cornerstone OnDemand',
 'Crelate',
 'Resume Parsing Software'
 ]

herramientas_web = [
 'Apache Kafka',
 'Cypress',
 'GitLab',
 'Apache Spark',
 'Ganache',
 'Plotly',
 'GraphQL',
 'Laravel',
 'Webpack',
 'Asana',
 'Vue.js',
 'Bootstrap',
 'Zapier',
 'Docker',
 'Confluence',
 'Visual Studio Code',
 'Sass',
 'Spring Boot',
 'Sublime Text',
 'WordPress Development',
 'Scrum',
 'JIRA',
 'Agile Methodology',
 'Redux',
 'Bitbucket',
 'MongoDB',
 'GitHub',
 'REST API',
 'Jenkins',
 'D3.js',
 'WebSockets',
 'JavaScript Frameworks (e.g., React, Angular, Vue)',
 'PostgreSQL',
 'ELK Stack (Elasticsearch, Logstash, Kibana)',
 'CI/CD (Continuous Integration/Continuous Deployment)',
 'Containerization',
 'Hive',
 'Apache',
 'WordPress',
 'Flask-RESTful',
 'ASP.NET',
 'OpenCV',
 'Django',
 'Python',
 'PHP',
 'Express.js',
 'Git',
 'React',
 'Airtable',
 'Node.js',
 'Kubernetes',
 'Nginx',
 'Web Development Frameworks (Flask, Django)',
 'Flask',
 'Ruby on Rails',
 'Swagger',
 'Ruby',
 'SQL',
 'Technical Writing',
 'Angular',
 'LESS',
 'Front-End Development (HTML, CSS, JavaScript)',
 'Power BI',
 'Responsive Web Design',
 'UI/UX Design'
 ]


puestos_data = [
 'Analista de Datos Financieros',
 'Investigador en Aprendizaje Profundo',
 'Ingeniero de Datos en Inteligencia Artificial',
 'Analista de Datos de Marketing',
 'Analista de Datos de Imágenes',
 'Ingeniero de Datos en Tiempo Real',
 'Analista de Datos de Usuarios',
 'Científico de Datos en Genómica',
 'Analista de Datos Avanzados',
 'Ingeniero de Datos en Aprendizaje Profundo en el Edge',
 'Especialista en Procesamiento de Lenguaje Natural',
 'Científico de Datos en Procesamiento de Audio',
 'Analista de Datos en Análisis de Sentimientos',
 'Analista de Datos de Series Temporales',
 'Científico de Datos en Robótica',
 'Arquitecto de Datos',
 'Analista de Datos',
 'Especialista en Datos de Mercado',
 'Analista de Datos en Predicción',
 'Ingeniero de Datos en Procesamiento de Texto',
 'Analista de Datos Empresariales',
 'Especialista en Datos de Sensores IoT',
 'Ingeniero de Datos en la Nube',
 'Científico de Datos en Sistemas de Recomendación',
 'Investigador en Aprendizaje por Refuerzo',
 'Desarrollador Machine Learning',
 'Especialista en Análisis de Datos en Salud',
 'Ingeniero de Datos en Análisis de Video',
 'Data Scientist',
 'Analista de Datos de Ciencia',
 'Data Analytics',
 'Especialista en Analítica de Datos',
 'Científico de Datos',
 'Arquitecto de Modelos de Aprendizaje Profundo',
 'Analista de Minería de Datos',
 'Especialista en Big Data',
 'Especialista en Datos de Comportamiento del Consumidor',
 'Analista de Datos en Optimización',
 'Analista de Datos Geoespaciales',
 'Ingeniero de Datos',
 'Científico de Datos en Deep Learning',
 'Ingeniero de Datos de Seguridad',
 'Desarrollador Machine Leraning',
 'Analista de Datos en Redes Neuronales',
 'Ingeniero de Datos en Procesamiento de Señales Biomédicas',
 'Ingeniero de Datos en Visión por Computadora',
 'Especialista en Datos de Sensores',
 'Ingeniero de Datos en Procesamiento de Señales',
 'Especialista en Visualización de Datos',
 'Ingeniero de Machine Learning',
 'Científico de Datos en IoT (Internet de las Cosas)',
 'Ingeniero de Aprendizaje Automático'
]

puestos_finanzas = [
 'Director de Operaciones Financieras',
 'Controller Financiero',
 'Auditor Financiero',
 'Analista de Datos de Salud',
 'Analista de Impuestos',
 'Gerente de Finanzas Corporativas',
 'Gerente de Relaciones Financieras',
 'Analista de Riesgos Financieros',
 'Director de Estrategia Financiera',
 'Analista de Rendimiento Financiero',
 'Consultor de Finanzas Empresariales',
 'Analista de Fusiones y Adquisiciones',
 'Gestor de Riesgos Financieros',
 'Especialista en Finanzas Personales',
 'Analista de Mercados',
 'Gerente de Cuentas Corporativas',
 'Gerente de Finanzas de Proyectos',
 'Gerente de Desarrollo Comercial',
 'Analista de Inversiones',
 'Analista Financiero',
 'Especialista en Análisis de Crédito',
 'Analista de Tesorería',
 'Director de Planificación Financiera',
 'Economista',
 'Analista de Finanzas Corporativas',
 'Analista de Cumplimiento Financiero',
 'Asesor Financiero',
 'Analista de Finanzas de Energía',
 'Especialista en Finanzas',
 'Analista de Estrategia de Negocios',
 'Analista de Costos',
 'Contador Fiscal',
 'Gerente de Finanzas',
 'Gerente de Desarrollo de Negocios',
 'Analista de Crédito',
 'Encargado de Ventas',
 'Encargado de Compras',
 'Director de Finanzas de la Cadena de Suministro',
 'Analista de Presupuesto',
 'Facturación y Cobros'
]

puestos_RRHH = [
'Especialista en Selección de Personal',
 'Especialista en Cultura Organizacional',
 'Comunity Mannager',
 'Consultor de Desarrollo de Talento',
 'Coordinador de Selección de Personal',
 'Analista de Datos de RRHH',
 'Analista de Recursos Humanos',
 'Especialista en Retención de Personal',
 'Especialista en Adquisición de Talento',
 'Analista de Recrutamiento',
 'Director de Desarrollo Organizacional',
 'Reclutador Corporativo',
 'Reclutador de Personal',
 'Especialista en Evaluación de Talento',
 'Especialista en Relaciones Laborales',
 'Gerente de Recursos Humanos y Talento',
 'Consultor de Reclutamiento',
 'Analista de RRHH',
 'Analista de Talento y Desarrollo',
 'Gerente de Bienestar de Empleados',
 'Especialista en Gestión de Desempeño',
 'Analista de Compensación y Beneficios',
 'Especialista en Diversidad e Inclusión',
 'Especialista en Gestión de Talento',
 'Especialista en Administración de Personal',
 'Director de Recursos Humanos',
 'Recepcionista',
 'Especialista en Employer Branding',
 'Especialista en Comunicación Interna',
 'Coordinador de Recursos Humanos',
 'Analista de Nóminas',
 'Consultor de Recursos Humanos',
 'Gerente de Desarrollo de Empleados',
 'Traductor de Idiomas',
 'Especialista en Capacitación y Desarrollo',
 'Gerente de Selección de Personal',
 'Coach de Negocios',
 'Gerente de Adquisición de Talento',
 'Gerente de Recursos Humanos'
]

puestos_web = [
 'Desarrollador Web Frontend CSS',
 'Ingeniero de Software Back-end Django',
 'Diseñador de Experiencia de Usuario (UX)',
 'Desarrollador Frontend Senior',
 'Desarrollador Back-end',
 'Desarrollador de Aplicaciones Móviles iOS',
 'Desarrollador Web Full Stack .NET',
 'Desarrollador Web Frontend React',
 'Desarrollador de Aplicaciones Móviles',
 'Desarrollador Back-end Java',
 'Ingeniero de Software Frontend SASS',
 'Desarrollador de Aplicaciones Web Python',
 'Desarrollador de Software Frontend',
 'Desarrollador de Software de Control',
 'Desarrollador Web Full Stack Angular',
 'Django Developer',
 'Desarrollador Web Full Stack Laravel',
 'Ingeniero de Software Web',
 'Ingeniero de Software Full Stack PHP',
 'Desarrollador de Aplicaciones Web',
 'Desarrollador de Software Java Web',
 'Ingeniero de Software Back-end',
 'Desarrollador de Software',
 'Ingeniero de Software Frontend TypeScript',
 'Desarrollador de Aplicaciones Web Ruby on Rails',
 'Arquitecto de Sistemas Web',
 'Desarrollador Back-end Python',
 'FullStack',
 'Ingeniero de Software Frontend',
 'Desarrollador de Aplicaciones Web Full Stack',
 'Diseñador de Interfaz de Usuario (UI/UX)',
 'Ingeniero de Software Frontend Vue.js',
 'Desarrollador Frontend',
 'Ingeniero de Software Full Stack',
 'Ingeniero de Software Back-end Node.js',
 'Desarrollador Frontend JavaScript',
 'Desarrollador Frontend HTML5',
 'Desarrollador Web Frontend Bootstrap'
]



empresas = [
    'Ingeniería Avanzada S.L.',
 'SmartSolutions Consulting',
 'MediCure Hospitals Group',
 'DataMasters Analytics',
 'MediConnect Healthcare',
 'Quality Products Distribution',
 'GreenTech Ventures',
 'Advanced Robotics Systems',
 'EcoScape Landscaping',
 'ProTech Access Control',
 'BlueOcean Technologies',
 'DataWave Technologies',
 'Creative Arts Studio',
 'Architectural Innovations',
 'GreenTech Industries',
 'Swift Transportation Services',
 'TechWizards Software',
 'Elite Fashion Boutique',
 'Modern Home Builders',
 'Sunrise Pharmaceuticals',
 'TechGenius Software',
 'Swift Cargo Shipping',
 'MediCenter Hospitals',
 'HealthCare Solutions Group',
 'Elite Sports Gear',
 'Swift Express Shipping',
 'Advanced Robotics Engineering',
 'AutoRevolution Automotive',
 'SmartCity Technologies',
 'Mega Autos Importadora',
 'Eco-Friendly Products Inc.',
 'TechFusion Solutions',
 'TechPro Consulting LLC',
 'Quality Supplies Inc.',
 'DataQuest Analytics',
 'Quality Supplies Distributors',
 'GreenPlanet Investments',
 'ProTech Surveillance Services',
 'Quality Foods Distribution',
 'DataGenius Innovations',
 'Architectural Masterpieces',
 'Industrial Engineering Group',
 'Creative Edge Design',
 'Quality Products Distributors',
 'MediCare Health Services',
 'HealthCare Innovations',
 'Global Trade Network',
 'Tech Solutions S.A. de C.V.',
 'Global Supply Chain Solutions',
 'Modern Interiors Design',
 'ProTech Surveillance Systems',
 'Innovative Systems Inc.',
 'Industrial Solutions Co.',
 'Ingeniería y Diseño Industrial',
 'Golden Harvest Agroexport',
 'AutoMasters Auto Repair',
 'Creative Design Group',
 'AutoMasters Dealership',
 'TechWave IT Solutions',
 'EcoSustainable Solutions',
 'Precision Electronics Inc.',
 'GreenEco Investments',
 'DataHub Analytics',
 'ProTech Alarm Systems',
 'MediCura Healthcare',
 'Global Marketing Agency',
 'Digital World Technologies',
 'Eco Energía Corporation',
 'BlueSky Aerospace Industries',
 'Swift Delivery Logistics',
 'Architectural Creations',
 'Precision Motors Inc.',
 'DataWorks Systems',
 'Architects & Associates',
 'Precision Instruments Corp.',
 'Swift Logistics Solutions',
 'Digital Marketing Experts',
 'AutoTech Innovations',
 'Food Delights Ltda.',
 'Innovative Technologies Ltd.',
 'Swift Express Cargo',
 'EcoCycle Recycling',
 'DataPro Consulting',
 'GreenTech Innovations',
 'HealthWave Pharmaceuticals',
 'Precision Manufacturing Solutions',
 'SmartGrid Energy Solutions',
 'DataVision Innovations',
 'Elite Travel Adventures',
 'GreenLife Ventures',
 'Creative Media Productions',
 'BlueStar Technologies',
 'SmartLiving Technologies',
 'Swift Cargo Logistics',
 'Creative Visions Studio',
 'Smart Energy Solutions',
 'Elite Fitness Center',
 'BlueWave Internet Services',
 'Modern Living Design',
 'AutoVision Auto Parts',
 'Modern Construction Ltd.',
 'Global Enterprises Network',
 'AutoDrive Automotive',
 'DataPower Solutions',
 'Advanced Materials Innovations',
 'Quality Motors Corporation',
 'Precision Tools Ltd.',
 'Global Solutions Consulting',
 'EcoVista Environmental',
 'Big Data Strategies',
 'InfoTech Analytics Group',
 'Global Logistics Ltd.',
 'Industrial Solutions Group',
 'BlueSky Communications',
 'ProTech Security Systems',
 'Precision Manufacturing Systems',
 'Elite Expeditions',
 'MediWell Healthcare',
 'Digital Insights Corp.',
 'Analytics Innovators Inc.',
 'HealthGuard Pharmaceuticals',
 'ProTech Security Services',
 'Digital Harmony Solutions',
 'DigitalXpress Solutions',
 'Swift Global Logistics',
 'MediLife Healthcare',
 'Digital Innovations Co.',
 'Global Travel Adventures',
 'EcoEnergy Solutions',
 'Modern Workspace Design',
 'Industrial Engineering Solutions',
 'DataWave Solutions',
 'Industrial Solutions Inc.',
 'Global Resources Network',
 'Construcciones Modernas S.A.',
 'GreenLeaf Organics',
 'DataSense Analytics',
 'Industrial Automation Solutions',
 'BlueStream Communications',
 'Dynamic Software Solutions',
 'TechSolutions Development',
 'Architectural Visionaries',
 'SmartPhone Technologies',
 'HealthLine Pharmaceuticals',
 'Data Insights Corporation',
 'Architectural Excellence',
 'Architectural Wonders',
 'Advanced Materials Research',
 'Modern Homes Development',
 'DataTech Solutions',
 'Quality Foods Group',
 'DataGenius Analytics',
 'HealthTech Pharmaceuticals',
 'Smart Home Solutions',
 'DataFusion Technologies',
 'TechNex IT Services',
 'Advanced Materials Inc.',
 'Healthy Foods International',
 'Advanced Robotics Technologies',
 'BlueStar Communications',
 'Creative Concepts Inc.',
 'Digital Dynamics Inc.',
 'DataCraft Labs',
 'Elite Outdoor Adventures',
 'Creative Minds Academy',
 'DataPro Analytics Group',
 'Precision Manufacturing Inc.',
 'Solar Power Solutions'
]

idioma1 = ['Inglés (básico)', 'Inglés (intermedio)', 'Inglés (avanzado)', 'Inglés (nativo)']
idioma2 = ['Alemán','Francés','Italiano','Japonés','Portugués']
nivel2 = ['(básico)', '(intermedio)', '(avanzado)']